server {
    listen 80;
    server_name stunnel.b0mb.local ovpn.b0mb.local api.b0mb.local www.b0mb.local;
    return 301 https://$host$request_uri;
}

server {
    listen 4430 ssl;
    server_name api.b0mb.local;

    ssl_certificate /etc/nginx/certs/b0mb.crt;
    ssl_certificate_key /etc/nginx/certs/b0mb.key;

    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 4430 ssl;
    server_name b0mb.local www.b0mb.local;

    ssl_certificate /etc/nginx/certs/b0mb.crt;
    ssl_certificate_key /etc/nginx/certs/b0mb.key;

    root /usr/share/nginx/f4k3;
    index index.html;
    error_page 404 403 500 502 503 504 /err.html;

    location / {
        try_files $uri $uri/ =404;
    }
    location ~ /\. {
        deny all;
        return 403;
    }
}
