worker_processes auto;

events {
    worker_connections 1024;
}

stream {
    resolver 127.0.0.11 valid=30s;

    map $ssl_preread_server_name $backend {
        api.b0mb.local      127.0.0.1:4430;
        www.b0mb.local      127.0.0.1:4430;
        b0mb.local          127.0.0.1:4430;
        stunnel.b0mb.local  stunnel:8443;
        ovpn.b0mb.local     ovpn:444;
        default             127.0.0.1:4430;
    }

    server {
        listen 443;
        ssl_preread on;
        proxy_pass $backend;
    }
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    include /etc/nginx/conf.d/*.conf;
}

